# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run:
          name: Install dependencies and build project
          command: 'echo "Installing dependencies and building project"'
      - run:
          name: Update APT
          command: 'sudo apt-get update'
      - run:
          name: Install GCC
          command: 'sudo apt-get install -y gcc g++'
      - run:
          name: Install MAKE
          command: 'sudo sudo apt-get install -y make'
      - run:
          name: Build MAKE
          command: 'make'
      - sonarcloud/scan

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.1

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud          
